"""Initial Setup

Revision ID: 42a4036c86d5
Revises: 
Create Date: 2026-03-12 15:45:46.547188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42a4036c86d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.drop_table('users')
    op.drop_table('address')
    op.drop_table('employer')
    op.drop_table('projects')
    op.drop_table('companies')
    op.drop_table('interns')
    op.drop_table('questions')
    op.drop_table('jobs')
    op.drop_table('apply')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('apply_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('apply_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('intern_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.intern_id'], name=op.f('apply_intern_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['jobs.job_id'], name=op.f('apply_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apply_id', name=op.f('apply_pkey'))
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('internship_mode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('application_deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.employer_id'], name=op.f('jobs_employer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('jobs_pkey'))
    )
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('questionaire', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), server_default=sa.text("'N/A'::text"), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('questions_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', name=op.f('questions_pkey'))
    )
    op.create_table('interns',
    sa.Column('intern_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('course', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('college', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('about_me', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('tech_stack', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('job_type', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('interns_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intern_id', name=op.f('interns_pkey'))
    )
    op.create_table('companies',
    sa.Column('companies_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('companies_id', name=op.f('companies_pkey'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intern_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.intern_id'], name=op.f('projects_intern_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('projects_pkey'))
    )
    op.create_table('employer',
    sa.Column('employer_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('companies_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companies_id'], ['companies.companies_id'], name=op.f('employer_companies_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('employer_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employer_id', name=op.f('employer_pkey'))
    )
    op.create_table('address',
    sa.Column('address_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('address_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intern_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.intern_id'], name=op.f('address_intern_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id', name=op.f('address_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('availability',
    sa.Column('availability_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('weekly_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('internship_duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location_preference', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('expected_salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intern_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.intern_id'], name=op.f('availability_intern_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('availability_id', name=op.f('availability_pkey'))
    )
    # ### end Alembic commands ###
